### ISSUE TITLE
Shared CSS Properties

### ISSUE THREAD

**Issue by cyouh95** [jefferyclanton/prj-rev-bwfs-dasmoto#2]
For properties shared among multiple elements, such as `font-family: helvetica`, you could use comma-separated selectors to style all of them at once:

```css
h1, h2, .blue {
  font-family: helvetica;
}
```

Alternatively, if you want to specify `font-family: helvetica` for all your elements (including the `p` and `h3` elements), you could use `body` as your selector - all the children elements of `body` would then automatically inherit this property without you needing to specify it again.

```css
body {
  font-family: helvetica;
}
```
